In [2]:
import pickle

In [3]:
with open('dqn_search_results_CVCL_0292_k4_n5.pkl', 'rb') as f:
    dqn_out = pickle.load(f)
with open('search_results_beam_k4_n5_debug.pkl', 'rb') as f:
    beam_out = pickle.load(f)

In [4]:
beam_out = beam_out[(beam_out['target_cl'] == 'CVCL_0292') & (beam_out['covered_threshold'] == True)].copy()
dqn_out = dqn_out[dqn_out['covered_threshold'] == True].copy()

In [5]:
beam_out

,search_id,type_of_search,n_steps,k,n_paths,beta,blend,threshold,starting_cl,target_cl,...,step,path_type,is_best_at_step,is_success,covered_threshold,end_position,drug_sequence,genes_targeted,cell_path,final_distance
211,54,k_path_beam,5,4,None,None,2,0.5,CVCL_0028,CVCL_0292,...,5.0,threshold,True,False,True,"[-1.0052910311157153, -0.19204741419877805, 1....","[[('Alpelisib', 5.0, 'uM')], [('Doxorubicin (h...","[(pik3ca,), (top2a, top2b, top1), (cckbr,), (d...","[[CVCL_0028, None], [CVCL_0028, None], [CVCL_0...",2.810529
446,101,k_path_beam,5,4,None,None,2,0.5,CVCL_0069,CVCL_0292,...,5.0,threshold,True,False,True,"[-0.9961060374022226, 0.17049027994322752, 1.2...","[[('Capmatinib', 5.0, 'uM')], [('olaparib', 5....","[(met,), (parp3, parp2, parp1), (ptgs2,), (pgr...","[[CVCL_0069, None], [CVCL_0069, None], [CVCL_1...",3.363243
447,101,k_path_beam,5,4,None,None,2,0.5,CVCL_0069,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.9961060374022226, 0.17049027994322752, 1.2...","[[('olaparib', 5.0, 'uM')], [('Capmatinib', 5....","[(parp3, parp2, parp1), (met,), (ptgs2,), (pgr...","[[CVCL_0069, None], [CVCL_0069, None], [CVCL_1...",3.363243
448,101,k_path_beam,5,4,None,None,2,0.5,CVCL_0069,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.9962255104547879, 0.17256664737956504, 1.2...","[[('Capmatinib', 5.0, 'uM')], [('olaparib', 5....","[(met,), (parp3, parp2, parp1), (pgr, nr3c2, a...","[[CVCL_0069, None], [CVCL_0069, None], [CVCL_1...",3.364161
449,101,k_path_beam,5,4,None,None,2,0.5,CVCL_0069,CVCL_0292,...,5.0,threshold,False,False,True,"[-1.2338843913993864, 0.0933060909670041, 1.50...","[[('Capmatinib', 5.0, 'uM')], [('olaparib', 5....","[(met,), (parp3, parp2, parp1), (ptgs2,), (pgr...","[[CVCL_0069, None], [CVCL_0069, None], [CVCL_1...",3.375819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10413,2217,k_path_beam,5,4,None,None,2,0.5,CVCL_C466,CVCL_0292,...,4.0,threshold,False,False,True,"[-0.019135803558902695, 0.4606565497840799, 0....","[[('Bortezomib', 5.0, 'uM')], [('Brimonidine',...","[(psmb1, psmd8, psmb7, psmd3, psma3, psmb3, ps...","[[CVCL_C466, None], [CVCL_1716, CVCL_0292], [C...",3.908267
10414,2217,k_path_beam,5,4,None,None,2,0.5,CVCL_C466,CVCL_0292,...,5.0,threshold,True,False,True,"[-0.3438086411393649, 0.49015154563351865, 1.4...","[[('Bortezomib', 5.0, 'uM')], [('Drospirenone'...","[(psmb1, psmd8, psmb7, psmd3, psma3, psmb3, ps...","[[CVCL_C466, None], [CVCL_1716, CVCL_0292], [C...",3.805223
10415,2217,k_path_beam,5,4,None,None,2,0.5,CVCL_C466,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.33942132820298665, 0.48791017484818594, 1....","[[('Bortezomib', 5.0, 'uM')], [('Drospirenone'...","[(psmb1, psmd8, psmb7, psmd3, psma3, psmb3, ps...","[[CVCL_C466, None], [CVCL_1716, CVCL_0292], [C...",3.810613
10416,2217,k_path_beam,5,4,None,None,2,0.5,CVCL_C466,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.33567282601505877, 0.48584783286041544, 1....","[[('Bortezomib', 5.0, 'uM')], [('Filgotinib', ...","[(psmb1, psmd8, psmb7, psmd3, psma3, psmb3, ps...","[[CVCL_C466, None], [CVCL_1716, CVCL_0292], [C...",3.811684
10417,2217,k_path_beam,5,4,None,None,2,0.5,CVCL_C466,CVCL_0292,...,5.0,threshold,False,False,True,"[-0.3313047806104696, 0.48402269805553627, 1.4...","[[('Bortezomib', 5.0, 'uM')], [('Brimonidine',...","[(psmb1, psmd8, psmb7, psmd3, psma3, psmb3, ps...","[[CVCL_C466, None], [CVCL_1716, CVCL_0292], [C...",3.817779

In [16]:
dqn_out[dqn_out['step'] < 5]

,search_id,type_of_search,n_steps,k,n_paths,beta,blend,threshold,starting_cl,target_cl,...,step,path_type,is_best_at_step,is_success,covered_threshold,end_position,drug_sequence,genes_targeted,cell_path,final_distance
28,10,dqn_guided_beam,5,4,None,None,2,0.5,CVCL_0334,CVCL_0292,...,4,threshold,False,False,True,"[-1.4429295010076126, 0.2953660403174846, 1.18...","[[('(S)-Crizotinib', 5.0, 'uM')], [('Irinoteca...","[(eml4, alk, ros1, npm1, met), (top1mt, top1),...","[[CVCL_0334, None], [CVCL_0334, CVCL_1716], [C...",3.363233
29,10,dqn_guided_beam,5,4,None,None,2,0.5,CVCL_0334,CVCL_0292,...,4,threshold,True,False,True,"[-1.341523777949026, 0.2968937155561514, 1.118...","[[('(S)-Crizotinib', 5.0, 'uM')], [('Volaserti...","[(eml4, alk, ros1, npm1, met), (plk1,), (cdk4,...","[[CVCL_0334, None], [CVCL_0334, None], [CVCL_0...",3.331655
90,17,dqn_guided_beam,5,4,None,None,2,0.5,CVCL_0459,CVCL_0292,...,4,threshold,True,False,True,"[-0.47989506857952957, -0.9958886765823323, 2....","[[('Rucaparib (phosphate)', 5.0, 'uM')], [('Af...","[(parp3, parp2, parp1), (erbb2, erbb4, egfr), ...","[[CVCL_0459, CVCL_1716], [CVCL_0459, CVCL_1716...",4.341287
174,32,dqn_guided_beam,5,4,None,None,2,0.5,CVCL_1517,CVCL_0292,...,4,threshold,False,False,True,"[-1.149769813501382, 0.3078953180606885, 2.159...","[[('olaparib', 5.0, 'uM')], [('Adenosine', 5.0...","[(parp3, parp2, parp1), (adora1, adora2a, ador...","[[CVCL_1517, None], [CVCL_1517, CVCL_1716], [C...",3.651447
175,32,dqn_guided_beam,5,4,None,None,2,0.5,CVCL_1517,CVCL_0292,...,4,threshold,True,False,True,"[-1.2063404939762514, 0.09660378217484061, 2.0...","[[('olaparib', 5.0, 'uM')], [('Adenosine', 5.0...","[(parp3, parp2, parp1), (adora1, adora2a, ador...","[[CVCL_1517, None], [CVCL_1517, CVCL_1716], [C...",3.556799